sudo: required
language: node_js
node_js:
    - 10.8.0
install:
  - npm i
script:
  - npm run lint
  - npx ng test --watch=false
  - npx ng build @chakray/fbc
  - BUILD=`date +%s`; sed -ie "s/BUILD/$BUILD/g" ./src/environments/environment.prod.ts
  - npx ng build --prod --deploy-url /rig/ --base-href /rig/
  - cp src/404.html dist/rig
cache:
    directories:
      - node_modules
deploy:
  - provider: pages
    local-dir: dist/rig
    github-token: $github
    skip-cleanup: true
    keep-history: true

