sudo: required
language: node_js
node_js:
    - 10.8.0
install:
  - npm i
script:
  - npm run lint
  - npx ng build @chakray/fbc
  - npx ng build @chakray/marked
  - npx ng build @chakray/gate
  - npx ng test --watch=false
  - BUILD=`date +%s`; sed -ie "s/BUILD/$BUILD/g" ./src/environments/environment.prod.ts
  - npx ng build --prod --deploy-url /rig/ --base-href /rig/
  - cp src/404.html dist/rig
  - npx typedoc projects/chakray/fbc/src
  - mv docs dist/rig
cache:
    directories:
      - node_modules
comment_before_deploy:
  - tar czf lib.tgz --transform 's/dist\/chakray\/fbc//g' dist/chakray/fbc
deploy:
  - provider: pages
    local-dir: dist/rig
    github-token: $github
    skip-cleanup: true
    keep-history: true
  - provider: releases
    api_key: $github
    file: 'lib.tgz'
    skip_cleanup: true
    draft: true
    on:
      tags: true
